version: '3.8'

x-logging: 
  &default-logging
  driver: json-file
  options:
    max-size: '100k'
    max-file: '1'

networks:
  shared-services:
    external: true

services:
  clean_architecture:
    container_name: clean_architecture
    restart: always
    build:
      context: .
      target: dev
    # user: '1000:1000'
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - '.:/application'
    # logging: *default-logging
    networks:
      - shared-services
    # ports:
    #   - "9229:9229"
    #   - "8081:8081"
